version: "3.1"

networks:
  mynetwork:
    name: mynetwork
    driver: bridge
    external: true
services:
  web:
    container_name: pharmalik-api
    build: .
    restart: on-failure
    ports:
      - 8001:8001
      - 5555:5555
    networks:
      - mynetwork
