version: "3.1"

networks:
  mynetwork:
    driver: bridge
services:
  web:
    container_name: pharmaLik-api
    build: .
    restart: on-failure
    ports:
      - 8001:8001
    networks:
      - mynetwork
